export const SEARCH_FOCUS='header/SEARCH_FOCUS'
export const SEARCH_BLUR='header/SEARCH_BLUR'
export const SHOW_MESSAGE='header/SHOW_MESSAGE'
export const HIDE_MESSAGE='header/HIDE_MESSAGE'
export const SHOW_MESSAGE_LIST='header/SHOW_MESSAGE_LIST'
